/*
 * #%L
 * **********************************************************************
 * ORGANIZATION  :  WSO2
 * PROJECT       :  WSO2 IoT Reference Architecture - Raspberry Pi Agent
 * FILENAME      :  org_wso2_iot_refarch_rpi_agent_DHTSensor.h
 * 
 * This file is part of the Pi4J project. More information about
 * this project can be found here:  http://www.wso2.com/
 * **********************************************************************
 * %%
 * Copyright (C) 2014 WSO2
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wso2_iot_refarch_rpi_agent_DHTSensor */

#ifndef _Included_com_pi4j_wiringpi_DHTSensor
#define _Included_com_pi4j_component_dht_DHTSensor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pi4j_component_dht_DHTSensor
 * Method:    readSensor
 * Signature: (II)[F
 */
JNIEXPORT void JNICALL Java_org_wso2_iot_refarch_rpi_agent_DHTSensor_readSensor
  (JNIEnv *, jobject, jint, jint);
int * readDHTRaw(int, int );

#ifdef __cplusplus
}
#endif
#endif